locales:
  wac:
    name: Wasco-Wishram Keyboards
    description: >-
      Mobile OS keyboards for the Wasco-Wishram language from the Divvun group
      at UiT.
  en:
    name: Wasco-Wishram Keyboards
    description: >-
      Mobile OS keyboards for the Wasco-Wishram language from the Divvun group
      at UiT.
  nb:
    name: Wasco-Wishram tastatur
    description: Mobiltastatur for Wasco-Wishram fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
